# Generated by Django 5.2.3 on 2025-07-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='particpant',
            new_name='partipant',
        ),
    ]
