# Generated by Django 5.2.3 on 2025-07-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_particpant_event_partipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='partipant',
            new_name='particpant',
        ),
    ]
