# Generated by Django 5.2.3 on 2025-07-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_partipant_event_particpant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='particpant',
        ),
    ]
