# Generated by Django 5.2.3 on 2025-07-24 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_event_particpant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='particpant',
            field=models.ManyToManyField(related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
