# Generated by Django 5.2.3 on 2025-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default.jpg', null=True, upload_to='events_asset'),
        ),
    ]
