# Generated by Django 5.2.3 on 2025-07-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_event_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='particpant',
            new_name='participant',
        ),
    ]
